with:
  token: ${{ secrets.METRICS_TOKEN }}
  user: jjh0w
  template: classic
  config_timezone: America/Sao_Paulo

  # Layout
  base: header, activity, community, repositories

  # Estatísticas gerais
  plugin_lines: yes
  plugin_lines_sections: base, repositories
  plugin_lines_history_limit: 1
  plugin_lines_delay: 0

  # Linguagens (o gráfico colorido)
  plugin_languages: yes
  plugin_languages_indepth: yes
  plugin_languages_details: bytes-size, percentage
  plugin_languages_limit: 8

  # Contribuições
  plugin_isocalendar: yes
  plugin_isocalendar_duration: half-year

  # Streaks (sequência de dias)
  plugin_stargazers: yes

  # Repositórios em destaque
  plugin_repositories: yes
  plugin_repositories_featured: jjh0w

  # Visual
  plugin_achievements: yes
  plugin_achievements_threshold: B
  plugin_achievements_secrets: yes
  plugin_achievements_display: detailed

  # Output
  filename: metrics.svg
  output_action: commit
