name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia 00:00
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jjh0w
          template: classic
          base: header, activity, repositories
          config_timezone: America/Sao_Paulo
          output_action: commit
          output_location: metrics.svg
