name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jjh0w
          template: classic
          config_timezone: America/Sao_Paulo

          # Layout base
          base: header, activity, community, repositories

          # Linhas de código
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_history_limit: 1
          plugin_lines_delay: 0

          # Linguagens (gráfico)
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8

          # Calendário de commits
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Conquistas (badges)
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_display: detailed

          # Repositórios
          plugin_repositories: yes
          plugin_repositories_featured: jjh0w

          # Saída
          filename: metrics.svg
          output_action: commit
